import '@fontsource-variable/manrope';
import '@fontsource/instrument-serif/latin-400-italic.css';
import './forma.css';

const paths = {
  arrow: '<path d="M5 19 19 5M5 5h14v14"/>', back: '<path d="m14 6-6 6 6 6M8 12h12"/>',
  send: '<path d="m7 17 10-10M7 7h10v10"/>', scan: '<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M7 12h10M12 7v10"/>',
  cash: '<rect x="3" y="5" width="18" height="14" rx="3"/><circle cx="12" cy="12" r="3"/><path d="M6 9h.01M18 15h.01"/>',
  home: '<path d="m3 10 9-7 9 7v10H3zM9 20v-7h6v7"/>', card: '<rect x="2" y="4" width="20" height="16" rx="4"/><path d="M2 10h20M6 15h4"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', eye: '<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
  check: '<path d="m5 12 4 4L19 6"/>', lock: '<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',
  coffee: '<path d="M4 8h12v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5zM16 9h2a3 3 0 0 1 0 6h-2M7 3v2m5-2v2"/>',
  plus: '<path d="M12 5v14M5 12h14"/>', chart: '<path d="M4 20V10m8 10V4m8 16v-6"/>',
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.arrow}</svg>`;
const logo = '<span class="forma-mark" aria-hidden="true"><i></i><i></i><i></i></span>';
const money = n => new Intl.NumberFormat('vi-VN').format(n) + ' ₫';
const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

document.querySelector('#app').innerHTML = `
<a class="skip" href="#prototype">Skip to interactive prototype</a>
<header class="case-header"><a class="portfolio-back" href="/#work">${icon('back')}<span>roylle.</span><span class="header-divider">/</span><span class="header-project">Selected work</span></a><a class="header-link" href="#approach">Behind the design ${icon('arrow')}</a></header>
<main>
<section class="case-hero">
  <div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> INDEPENDENT CONCEPT · MOBILE APP · 2026</div><a class="forma-brand" href="#prototype" aria-label="Forma, try the prototype">${logo}forma</a><h1>Money moves.<br><em>Life happens.</em></h1><p class="hero-description">An everyday banking experience that makes room for living. Send, pay, and take cash out — with a little more clarity at every step.</p><a class="primary-link" href="#prototype">Try the experience ${icon('arrow')}</a><div class="hero-footnote"><span>01 / FINTECH</span><span>PRODUCT THINKING × INTERACTION DESIGN</span></div></div>
  <div class="hero-art" aria-label="Forma banking app interface preview"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-caption">A LITTLE LESS BANKING.<br>A LITTLE MORE LIVING.</span><div class="visual-phone"><div class="phone-notch"></div><div class="mini-status">9:41 <span>▴ ▴ ▰</span></div><div class="mini-greeting"><span>Chào buổi sáng,<strong>Minh Anh ${'↗'}</strong></span><span class="avatar">MA</span></div><div class="mini-balance"><span>Tổng số dư</span><strong>24.850.000 <small>₫</small></strong><span>Tài khoản thanh toán · 0826</span><div class="mini-balance-bottom">${logo}<span>VND ACCOUNT</span></div></div><div class="mini-shortcuts"><span>${icon('send')}Chuyển tiền</span><span>${icon('scan')}Thanh toán</span><span>${icon('cash')}Rút tiền</span></div><div class="mini-section-title">Một chút cho tương lai ${icon('arrow')}</div><div class="mini-saving"><span class="saving-icon">${icon('plus')}</span><div>Chuyến đi tiếp theo<small>3.500.000 / 5.000.000 ₫</small><span class="progress-bar"><i></i></span></div><strong>70%</strong></div><div class="mini-section-title">Gần đây <span>Hôm nay</span></div><div class="mini-transaction"><span class="transaction-icon">${icon('coffee')}</span><div>The Coffee House<small>Ăn uống · 08:42</small></div><strong>−65.000 ₫</strong></div><div class="mini-nav"><span class="selected">${icon('home')}Tổng quan</span><span>${icon('card')}Thẻ</span><span>${icon('clock')}Giao dịch</span></div></div><div class="floating-note">${icon('check')}<span>All set.<strong>Back to your day.</strong></span></div><span class="art-number">f / 01</span></div>
</section>
<section class="project-facts" aria-label="Project details"><div><span>THE PROJECT</span><p>Everyday banking, reimagined.</p></div><div><span>DESIGN SCOPE</span><p>UX flows · Visual system · Prototype</p></div><div><span>PLATFORM</span><p>Mobile app / Vietnamese interface</p></div><div><span>PROJECT STATUS</span><p><i class="status-dot"></i> Independent concept</p></div></section>
<section class="approach section-pad" id="approach"><div class="eyebrow">01 / THE INTENTION</div><div class="approach-grid"><h2>Less second-guessing.<br><em>More getting on with it.</em></h2><div><p>Moving money should feel understandable. This concept brings three everyday tasks into a familiar rhythm: choose, review, confirm.</p><p class="muted">A design hypothesis for people who bank on the go. The flows and visual system are original explorations, informed by interface references from Mobbin. User research and usability validation are next steps.</p></div></div><div class="principles"><article><span>01</span><h3>Know where you stand.</h3><p>Your balance, recent activity, and everyday actions share one clear starting point.</p></article><article><span>02</span><h3>See it before you send it.</h3><p>Recipient, amount, and fee appear together before any simulated transaction.</p></article><article><span>03</span><h3>A way forward. A way back.</h3><p>Edit a transfer, cancel a cash code, or recover from an invalid amount without losing context.</p></article></div></section>
<section class="prototype-section section-pad" id="prototype"><div class="prototype-copy"><div class="eyebrow">02 / PLAY THE PROTOTYPE</div><h2>Your money.<br><em>Your next move.</em></h2><p>Pick a task and try it inside the app.<br>Every interaction uses sample data.</p><div class="scenario-list" role="group" aria-label="Choose a prototype scenario"><button class="scenario active" data-scenario="home" aria-pressed="true"><span class="scenario-icon">${icon('home')}</span><span><strong>The everyday overview</strong><small>Balance, cards, and recent activity</small></span>${icon('arrow')}</button><button class="scenario" data-scenario="transfer" aria-pressed="false"><span class="scenario-icon">${icon('send')}</span><span><strong>Send a little something</strong><small>Choose a recipient → review → send</small></span>${icon('arrow')}</button><button class="scenario" data-scenario="payment" aria-pressed="false"><span class="scenario-icon">${icon('scan')}</span><span><strong>Pay and be on your way</strong><small>Try a sample QR payment</small></span>${icon('arrow')}</button><button class="scenario" data-scenario="withdraw" aria-pressed="false"><span class="scenario-icon">${icon('cash')}</span><span><strong>Cash. Without the card.</strong><small>Choose an amount → create a cash code</small></span>${icon('arrow')}</button></div><div class="prototype-note">${icon('lock')}<p>Interactive design demo. No real accounts, bank connection, or money movement. Reloading resets the sample data.</p></div><button class="reset-button" id="reset-demo">Reset demo ${icon('back')}</button><p id="demo-status" class="sr-only" role="status"></p></div><div class="prototype-stage"><span class="stage-label">FORMA / INTERACTIVE PREVIEW</span><div class="device"><div class="device-status"><span>9:41</span><div class="dynamic-island"></div><span aria-hidden="true">▴ ▴ ▰</span></div><div class="demo-badge">BẢN MẪU · KHÔNG GIAO DỊCH THẬT</div><div id="bank-app" lang="vi"></div><div class="home-indicator"></div></div><span class="stage-caption">DESIGNED FOR EVERYDAY MOMENTS.</span></div></section>
<section class="system-section section-pad"><div class="eyebrow">03 / A QUIETER VISUAL LANGUAGE</div><div class="system-heading"><h2>Grounded in green.<br><em>Built around clarity.</em></h2><p>A deep evergreen anchors the interface. A soft citron adds warmth. Generous spacing gives important details a place to stand out.</p></div><div class="system-grid"><div class="type-tile"><span class="eyebrow">THE INTERFACE TYPEFACE</span><strong>Aa</strong><div><b>Manrope</b><span>Clear at a glance. Calm in the details.</span></div><p>0123456789 &nbsp; ₫</p></div><div class="color-tile color-evergreen"><span>01 / EVERGREEN</span><span>#163D32</span></div><div class="color-tile color-citron"><span>02 / CITRON</span><span>#DDEDAB</span></div><div class="color-tile color-paper"><span>03 / PAPER</span><span>#F4F4E9</span></div></div></section>
<section class="references section-pad"><div><div class="eyebrow">04 / REFERENCE & REFLECTION</div><h2>Inspired by patterns.<br><em>Made for this concept.</em></h2></div><div><p>Mobbin references informed the balance hierarchy, action shortcuts, and transfer sequence. Screens and branding were designed for Forma; reference artwork is not embedded in the project.</p><a href="https://mobbin.com/screens/cc7517f5-b31a-4ac2-93be-9db60c2af6d8" target="_blank" rel="noopener noreferrer">N26 · Balance & action shortcuts ${icon('arrow')}</a><a href="https://mobbin.com/screens/6c2bac17-2f8f-468d-bc8f-c77b4cf7ea5b" target="_blank" rel="noopener noreferrer">Monzo · Account card & activity ${icon('arrow')}</a><a href="https://mobbin.com/flows/73302e5a-3d9f-4626-a815-3c62b62c1c34" target="_blank" rel="noopener noreferrer">Grab · Bank transfer flow ${icon('arrow')}</a><p class="next-step">Next: test task completion and comprehension of fees, then validate ATM handoff and authentication with a banking partner. No research outcomes or live banking capability are claimed.</p></div></section>
</main><footer class="case-footer"><a href="/#work">${icon('back')} Back to selected work</a><span>ROYLLE · INDEPENDENT CONCEPT · 2026</span><a href="#">Back to top ↑</a></footer>`;

const app = document.querySelector('#bank-app');
const recipients = [{name:'Linh Nguyễn', initials:'LN', bank:'Forma', account:'•••• 1028'}, {name:'Tuấn Trần', initials:'TT', bank:'Forma', account:'•••• 6402'}, {name:'Mai Phạm', initials:'MP', bank:'Forma', account:'•••• 3915'}];
const initialTransactions = () => [{name:'The Coffee House', type:'Ăn uống · Hôm nay', amount:-65000, icon:'coffee'}, {name:'Lương tháng 9', type:'Thu nhập · Hôm qua', amount:18000000, icon:'plus'}, {name:'Linh Nguyễn', type:'Chuyển tiền · Hôm qua', amount:-250000, icon:'send'}];
let balance = 24850000, transactions = initialTransactions(), screen = 'home', flow = 'transfer', recipient = recipients[0], amount = '', note = '', hiddenBalance = false, cardLocked = false, cashDeadline = 0, timer, completedAmount = 0;
const names = {transfer:'Chuyển tiền', payment:'Thanh toán', withdraw:'Rút tiền không thẻ'};
const txRows = () => transactions.map(t=>`<div class="transaction"><span class="transaction-icon">${icon(t.icon)}</span><span class="transaction-info"><strong>${escape(t.name)}</strong><small>${escape(t.type)}</small></span><strong class="transaction-amount ${t.amount>0?'positive':''}">${t.amount>0?'+':'−'}${money(Math.abs(t.amount))}</strong></div>`).join('');
const nav = current => `<nav class="app-nav" aria-label="Điều hướng ứng dụng">${[['home','home','Tổng quan'],['cards','card','Thẻ'],['activity','clock','Giao dịch']].map(([id,ic,label])=>`<button data-go="${id}" ${id===current?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('')}</nav>`;
const top = (title, back='home') => `<div class="app-top"><button class="icon-button" data-go="${back}" aria-label="Quay lại">${icon('back')}</button><h3 tabindex="-1" class="app-heading">${title}</h3><span class="step-dot"></span></div>`;
const detailRow = (key,value) => `<div class="receipt-row"><span>${key}</span><strong>${value}</strong></div>`;
function setScreen(next, focus=true) { screen=next; render(); if(focus) app.querySelector('.app-heading, h3, input, button')?.focus({preventScroll:true}); }
function startFlow(next) {
  if(cashDeadline) { setScreen('cash-code'); return; }
  flow=next; amount=''; note=''; recipient=recipients[0];
  setScreen(next==='transfer'?'recipient':next==='payment'?'merchant':'amount');
  document.querySelectorAll('[data-scenario]').forEach(b=>{const active=b.dataset.scenario===next;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
}
function render() {
  if(timer) { clearInterval(timer); timer=undefined; }
  if(screen==='home') app.innerHTML=`<div class="app-content"><div class="app-greeting"><div><p>Chào buổi sáng,</p><h3 class="app-heading" tabindex="-1">Minh Anh <span>↗</span></h3></div><span class="avatar">MA</span></div><div class="balance-card"><div><span>Tổng số dư</span><button data-action="hide" aria-label="${hiddenBalance?'Hiện':'Ẩn'} số dư" aria-pressed="${hiddenBalance}">${icon('eye')}</button></div><strong>${hiddenBalance?'••••••••':money(balance)}</strong><p>Tài khoản thanh toán · 0826</p><div class="balance-footer">${logo}<span>VND ACCOUNT</span></div></div><div class="quick-actions">${[['transfer','send','Chuyển tiền'],['payment','scan','Thanh toán'],['withdraw','cash','Rút tiền']].map(([f,i,l])=>`<button data-flow="${f}"><span>${icon(i)}</span>${l}</button>`).join('')}</div><div class="app-section-title"><h4>Một chút cho tương lai</h4><span>70%</span></div><div class="savings"><span class="saving-icon">${icon('plus')}</span><div><strong>Chuyến đi tiếp theo</strong><small>3.500.000 / 5.000.000 ₫</small><span class="progress-bar"><i></i></span></div></div><div class="app-section-title"><h4>Gần đây</h4><button data-go="activity">Tất cả</button></div>${transactions.slice(0,2).map(t=>`<div class="transaction"><span class="transaction-icon">${icon(t.icon)}</span><span class="transaction-info"><strong>${escape(t.name)}</strong><small>${escape(t.type)}</small></span><strong class="transaction-amount ${t.amount>0?'positive':''}">${t.amount>0?'+':'−'}${money(Math.abs(t.amount))}</strong></div>`).join('')}</div>${nav('home')}`;
  if(screen==='cards') app.innerHTML=`<div class="app-content">${top('Thẻ của bạn')}<p class="app-muted">Một chiếc thẻ. Cho mọi ngày.</p><div class="virtual-card ${cardLocked?'locked':''}"><div>${logo}<strong>forma</strong></div><span class="card-chip"></span><strong class="card-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 0826</strong><div><span>MINH ANH NGUYEN</span><span>debit</span></div></div><div class="card-state">${icon(cardLocked?'lock':'check')} ${cardLocked?'Thẻ đã tạm khóa':'Thẻ đang hoạt động'}</div><p class="app-muted">Thẻ và thao tác khóa chỉ là mô phỏng trong prototype.</p><button class="app-primary" data-action="lock">${icon('lock')}${cardLocked?'Mở khóa thẻ mẫu':'Tạm khóa thẻ mẫu'}</button></div>${nav('cards')}`;
  if(screen==='activity') app.innerHTML=`<div class="app-content">${top('Lịch sử giao dịch')}<div class="activity-total"><span>Số dư hiện tại</span><strong>${hiddenBalance?'••••••••':money(balance)}</strong></div><p class="app-muted">Hoạt động trên tài khoản mẫu</p>${txRows()}</div>${nav('activity')}`;
  if(screen==='recipient') app.innerHTML=`<div class="app-content flow-content">${top('Chuyển tiền')}<span class="flow-step">01 / NGƯỜI NHẬN</span><h4 class="flow-title">Gửi đến ai hôm nay?</h4><p class="app-muted">Chọn một người nhận mẫu để bắt đầu.</p><div class="recipient-list">${recipients.map((r,i)=>`<button class="recipient-row" data-recipient="${i}"><span class="avatar avatar-${i}">${r.initials}</span><span><strong>${r.name}</strong><small>${r.bank} · ${r.account}</small></span>${icon('send')}</button>`).join('')}</div><div class="app-tip">${icon('lock')} Danh bạ mẫu. Không cần nhập thông tin cá nhân.</div></div>`;
  if(screen==='merchant') app.innerHTML=`<div class="app-content flow-content">${top('Thanh toán QR')}<span class="flow-step">01 / ĐIỂM THANH TOÁN</span><h4 class="flow-title">Một lần quét.<br>Xong một việc.</h4><div class="qr-sample">${icon('scan')}<span>QR MẪU</span></div><p class="app-muted centered">Dùng điểm thanh toán mẫu để trải nghiệm.<br>Prototype không mở camera.</p><div class="merchant"><span class="transaction-icon">${icon('coffee')}</span><div><strong>The Coffee House</strong><small>Điểm thanh toán mẫu · 0091</small></div></div><button class="app-primary" data-action="sample-qr">Dùng QR mẫu ${icon('arrow')}</button></div>`;
  if(screen==='amount') app.innerHTML=`<div class="app-content flow-content">${top(names[flow],flow==='transfer'?'recipient':flow==='payment'?'merchant':'home')}<span class="flow-step">${flow==='withdraw'?'01 / SỐ TIỀN':'02 / SỐ TIỀN'}</span><h4 class="flow-title">${flow==='withdraw'?'Bạn cần bao nhiêu?':'Một con số. Một ý định.'}</h4>${flow!=='withdraw'?`<div class="selected-recipient"><span class="avatar">${flow==='payment'?'TC':recipient.initials}</span><div><strong>${flow==='payment'?'The Coffee House':recipient.name}</strong><small>${flow==='payment'?'Điểm thanh toán mẫu · 0091':`${recipient.bank} · ${recipient.account}`}</small></div></div>`:'<p class="app-muted">Tạo mã rút tiền tại ATM Forma mẫu.<br>Mệnh giá 50.000 ₫ · Tối đa 5.000.000 ₫.</p>'}<form id="amount-form" novalidate><label for="transfer-amount">Số tiền (VND)</label><div class="amount-input-wrap"><input id="transfer-amount" name="amount" inputmode="numeric" autocomplete="off" placeholder="0" maxlength="12" value="${escape(amount)}" aria-describedby="amount-hint amount-error"><span>₫</span></div><p id="amount-hint" class="app-muted">Số dư khả dụng: ${money(balance)}</p><div class="amount-presets">${(flow==='payment'?[65000,100000,200000]:[100000,500000,1000000]).map(n=>`<button type="button" data-amount="${n}">${new Intl.NumberFormat('vi-VN').format(n)}</button>`).join('')}</div>${flow!=='withdraw'?`<label for="transfer-note">Lời nhắn <span>(không bắt buộc)</span></label><input id="transfer-note" name="note" maxlength="60" placeholder="Một lời nhắn nhỏ…" value="${escape(note)}">`:''}<p class="form-error" id="amount-error" role="alert"></p><button class="app-primary" type="submit">Tiếp tục ${icon('arrow')}</button></form><p class="fee-note">Phí giao dịch mẫu: 0 ₫</p></div>`;
  if(screen==='review') app.innerHTML=`<div class="app-content flow-content">${top('Kiểm tra thông tin','amount')}<span class="flow-step">${flow==='withdraw'?'02':'03'} / XÁC NHẬN</span><div class="review-hero"><span class="review-icon">${icon(flow==='withdraw'?'cash':flow==='payment'?'scan':'send')}</span><p>${names[flow]}</p><strong>${money(Number(amount))}</strong></div><div class="receipt">${detailRow(flow==='withdraw'?'Điểm rút tiền':'Người nhận',flow==='withdraw'?'ATM Forma · mẫu':flow==='payment'?'The Coffee House':recipient.name)}${flow==='transfer'?detailRow('Tài khoản',`${recipient.bank} ${recipient.account}`):''}${detailRow('Nguồn tiền','Tài khoản · 0826')}${detailRow('Phí giao dịch','0 ₫')}${detailRow('Tổng cộng',money(Number(amount)))}${note?detailRow('Lời nhắn',escape(note)):''}</div><p class="app-tip">${icon('lock')}${flow==='withdraw'?'Mã mẫu có hiệu lực 5 phút. Số dư chỉ thay đổi sau bước mô phỏng nhận tiền.':'Đây là giao dịch mô phỏng. Xác nhận để cập nhật số dư mẫu.'}</p><button class="app-primary" data-action="confirm">${flow==='withdraw'?'Tạo mã rút tiền mẫu':'Xác nhận giao dịch mẫu'} ${icon('check')}</button><button class="app-secondary" data-go="amount">Chỉnh sửa số tiền</button></div>`;
  if(screen==='cash-code') {
    app.innerHTML=`<div class="app-content flow-content"><div class="app-top"><h3 class="app-heading" tabindex="-1">Mã rút tiền của bạn</h3></div><span class="flow-step">03 / NHẬN TIỀN TẠI ATM MẪU</span><div class="review-hero"><span class="review-icon">${icon('cash')}</span><p>Số tiền rút</p><strong>${money(Number(amount))}</strong></div><div class="cash-code"><span>MÃ DEMO · KHÔNG DÙNG TẠI ATM THẬT</span><strong>DEMO 0826</strong><p>Hết hạn sau <b id="cash-countdown">05:00</b></p></div><ol class="cash-steps"><li>Chọn “Rút tiền không thẻ” tại ATM mẫu.</li><li>Nhập mã và kiểm tra số tiền.</li><li>Xác nhận nhận tiền trong mô phỏng.</li></ol><button class="app-primary" data-action="collect">Mô phỏng đã nhận tiền ${icon('check')}</button><button class="app-secondary" data-action="cancel-cash">Hủy mã rút tiền</button><p class="fee-note">Chưa trừ tiền trong tài khoản mẫu.</p></div>`;
    updateCountdown(); if(screen==='cash-code') timer=setInterval(updateCountdown,1000);
  }
  if(screen==='expired') app.innerHTML=`<div class="app-content flow-content">${top('Mã đã hết hạn')}<div class="success-symbol expired-symbol">${icon('clock')}</div><h4 class="success-title">Mình tạo mã mới nhé?</h4><p class="app-muted centered">Mã cũ đã hết hiệu lực.<br>Số dư mẫu chưa bị trừ.</p><button class="app-primary" data-flow="withdraw">Tạo mã mới</button><button class="app-secondary" data-go="home">Về tổng quan</button></div>`;
  if(screen==='success') app.innerHTML=`<div class="app-content flow-content"><span class="flow-step">GIAO DỊCH MẪU HOÀN TẤT</span><div class="success-symbol">${icon('check')}</div><h3 class="success-title app-heading" tabindex="-1">${flow==='withdraw'?'Tiền mặt, sẵn sàng.':flow==='payment'?'Thanh toán xong rồi.':'Đã gửi, thật nhẹ nhàng.'}</h3><p class="app-muted centered">${flow==='withdraw'?'Đã hoàn tất bước nhận tiền mô phỏng.':`Đến ${flow==='payment'?'The Coffee House':recipient.name}`}</p><strong class="success-amount">${money(completedAmount)}</strong><div class="receipt">${detailRow('Trạng thái','Thành công · mô phỏng')}${detailRow('Phí giao dịch','0 ₫')}${detailRow('Số dư còn lại',money(balance))}</div><button class="app-primary" data-go="home">Về tổng quan ${icon('home')}</button><button class="app-secondary" data-go="activity">Xem giao dịch mẫu</button></div>`;
  app.scrollTop=0;
}
function updateCountdown() {
  const seconds=Math.max(0,Math.ceil((cashDeadline-Date.now())/1000));
  if(!seconds) {cashDeadline=0;setScreen('expired');return;}
  const el=document.querySelector('#cash-countdown'); if(el) el.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
}
function complete() {
  if(!['review','cash-code'].includes(screen)) return;
  const value=Number(amount);
  if(!Number.isSafeInteger(value)||value<=0||value>balance) {setScreen('amount');return;}
  balance-=value; completedAmount=value;
  transactions.unshift({name:flow==='transfer'?recipient.name:flow==='payment'?'The Coffee House':'Rút tiền ATM Forma',type:`${names[flow]} · Vừa xong · Mẫu`,amount:-value,icon:flow==='transfer'?'send':flow==='payment'?'coffee':'cash'});
  cashDeadline=0;setScreen('success');
}
app.addEventListener('click', e=>{
  const button=e.target.closest('button');if(!button)return;
  if(button.dataset.go){setScreen(button.dataset.go);return;}
  if(button.dataset.flow){startFlow(button.dataset.flow);return;}
  if(button.dataset.recipient!==undefined){recipient=recipients[Number(button.dataset.recipient)];setScreen('amount');return;}
  if(button.dataset.amount){const input=app.querySelector('#transfer-amount');input.value=button.dataset.amount;amount=input.value;app.querySelector('#amount-error').textContent='';input.removeAttribute('aria-invalid');return;}
  switch(button.dataset.action){
    case 'hide': hiddenBalance=!hiddenBalance;render();app.querySelector('[data-action="hide"]')?.focus({preventScroll:true});break;
    case 'lock': cardLocked=!cardLocked;render();app.querySelector('[data-action="lock"]')?.focus({preventScroll:true});break;
    case 'sample-qr': amount='65000';setScreen('amount');break;
    case 'confirm': if(flow==='withdraw'){cashDeadline=Date.now()+5*60*1000;setScreen('cash-code');}else complete();break;
    case 'collect': if(Date.now()>=cashDeadline){cashDeadline=0;setScreen('expired');}else complete();break;
    case 'cancel-cash': cashDeadline=0;setScreen('home');document.querySelector('#demo-status').textContent='Cash code cancelled. Demo balance unchanged.';break;
  }
});
app.addEventListener('input',e=>{if(e.target.name==='amount')amount=e.target.value;if(e.target.name==='note')note=e.target.value;});
app.addEventListener('submit',e=>{
  e.preventDefault();if(e.target.id!=='amount-form')return;
  const input=app.querySelector('#transfer-amount');amount=input.value.trim();const value=Number(amount);
  let error='';
  if(!/^\d+$/.test(amount)||!Number.isSafeInteger(value)||value<1000)error='Nhập số tiền nguyên từ 1.000 ₫, chỉ gồm chữ số.';
  else if(value>balance)error='Số dư mẫu không đủ. Vui lòng nhập số tiền nhỏ hơn.';
  else if(flow==='withdraw'&&(value>5000000||value%50000!==0))error='Chọn bội số của 50.000 ₫, tối đa 5.000.000 ₫.';
  if(error){app.querySelector('#amount-error').textContent=error;input.setAttribute('aria-invalid','true');input.focus();return;}
  setScreen('review');
});
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{
  const next=button.dataset.scenario;
  if(cashDeadline){setScreen('cash-code');document.querySelector('#demo-status').textContent='Complete or cancel the current cash code before starting another task.';return;}
  if(next==='home'){setScreen('home');document.querySelectorAll('[data-scenario]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});}else startFlow(next);
  if(matchMedia('(max-width: 800px)').matches)document.querySelector('.device').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
}));
document.querySelector('#reset-demo').addEventListener('click',()=>{
  balance=24850000;transactions=initialTransactions();cashDeadline=0;hiddenBalance=false;cardLocked=false;amount='';note='';setScreen('home',false);
  document.querySelectorAll('[data-scenario]').forEach(b=>{const active=b.dataset.scenario==='home';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
  document.querySelector('#demo-status').textContent='Demo reset. Sample balance restored to 24,850,000 VND.';
});
render();
if(import.meta.hot)import.meta.hot.dispose(()=>clearInterval(timer));
