const base = 'https://www.behance.net/gallery/';

// Existing public projects are verified on the owner's Behance profile.
// Local concepts are explicitly identified and link to their own case study.
// Summaries describe the shown work; no business results or client claims are inferred.
export const projects = [
  { slug: 'grabroy', name: 'GrabRoy', subtitle: 'One super-app. One coherent interaction language.', category: 'app', type: 'Mobile app · Independent redesign', scope: 'IA, design system, 60 screens & prototype', local: true, presentation: 'device', image: '/projects/grabroy-home.webp', url: '/grabroy.html', summary: 'A systems-led super-app redesign study focused on cross-service consistency, reusable patterns and recoverable user journeys.', color: '#d8f0e2' },
  { slug: 'cryproy', name: 'CrypRoy', subtitle: 'Confidence for decisions that carry consequence.', category: 'app', type: 'Fintech · Independent redesign', scope: 'Spot trading flow, design system & prototype', local: true, presentation: 'device', image: '/projects/cryproy-home.webp', url: '/cryproy.html', summary: 'A focused spot-trading redesign exploring decision clarity, validation, processing feedback and recoverable outcomes.', color: '#ffe783' },
  { slug: 'forma', name: 'Forma', subtitle: 'Everyday banking. A little more human.', category: 'app', type: 'Mobile app · Banking concept', scope: 'Transfers, payments & cardless withdrawals', local: true, image: '/projects/forma.svg', url: '/forma.html', summary: 'An independent banking app concept with an interactive Vietnamese prototype. Explore transfers, sample QR payments and cardless withdrawals with clear review and confirmation steps.', color: '#e5ead7' },
  { slug: 'solace', name: 'SOLACE', subtitle: 'A softer side of furniture shopping.', category: 'web', type: 'E-commerce · UI/UX', scope: 'Website & mobile app', source: '144370095/UI-UX-Design-SOLACE-Funiture', summary: 'A furniture shopping interface explored across web and mobile. A quiet visual language gives the products room to breathe.', color: '#d8dfd9' },
  { slug: 'soundred', name: 'SoundRed', subtitle: 'Turning up the digital experience.', category: 'web', type: 'Website · UI design', scope: 'Audio & lighting website', source: '230708601/SoundRed-Am-thanh-Anh-sang-Website-UI', summary: 'Website UI for audio and lighting services. A dark canvas and vivid red accents echo the energy of a live event.', detail: true, color: '#310b0d' },
  { slug: 'datablue', name: 'DataBlue', subtitle: 'A clear interface for a connected world.', category: 'web', type: 'Website · Digital services', scope: 'Website, hosting & CRM', source: '230698403/H-tng-s-DataBlue-Website-Hosting-CRM', summary: 'A website design for digital infrastructure, bringing website, hosting and CRM services into one visual experience.', detail: true, color: '#152226' },
  { slug: 'tam-yen', name: 'Tâm Yên', subtitle: 'A little more space to find your calm.', category: 'web', type: 'Website · Wellness', scope: 'Wellness & yoga website', source: '229610067/UIUX-Website-Tam-Yen', summary: 'A wellness and yoga website concept, with a gentle palette and imagery that make space for a calmer digital experience.', detail: true, color: '#e2dcc7' },
  { slug: 'greenspace', name: 'GREENSPACE', subtitle: 'Connecting artifacts and digital experiences.', category: 'app', type: 'Application · AR & CMS', scope: 'Artifact app & content management', source: '230749715/GREENSPACE-AR-CMS-UIUX-APP-Hin-Vt', summary: 'An interface exploration for an artifact application and AR content management. The project brings a collection of physical objects into a digital context.', detail: true, color: '#dbe5e3' },
  { slug: 'healthytrack', name: 'HealthyTrack', subtitle: 'Making room for clarity in complex systems.', category: 'app', type: 'ERP · UX wireframes', scope: 'ERP wireframes & mini UX case study', source: '230931797/HealthyTrack-ERP-Wireframe-(Mini-UX-Casestudy)', summary: 'An ERP wireframe project presented as a mini UX case study. It explores interface structure and the organization of information for a health-related system.', detail: true, color: '#e7e7e7' },
  { slug: 'dai-quoc-viet', name: 'Đại Quốc Việt', subtitle: 'A website interface exploration.', category: 'web', type: 'Website · UI/UX', scope: 'Website design', source: '229677019/Di-Quc-Vit-UIUX', summary: 'A website UI/UX project. Explore the original visual presentation and interface work on Behance.', color: '#dbe0e8' },
  { slug: 'metafox', name: 'MetaFOX', subtitle: 'Exploring the world of digital collectibles.', category: 'app', type: 'Mobile app · UI/UX', scope: 'NFT application design', source: '229675567/MetaFOX-NFT-APP-UI-UX-Project', summary: 'A mobile UI/UX design exploration for an NFT application, presented through the MetaFOX visual identity.', color: '#303044' },
  { slug: 'building-management', name: 'Building Management', subtitle: 'The structure behind the experience.', category: 'app', type: 'System · UX wireframes', scope: 'Building management wireframes', source: '230073977/Wireframe-UX-Building-Management', summary: 'A wireframe exploration of a building management interface, focusing on structure before visual detail.', color: '#d4dde1' },
  { slug: 'motion', name: 'Just a Motion', subtitle: 'A small experiment in movement.', category: 'play', type: 'Exploration · Motion', scope: 'Motion study', source: '234997197/Just-A-Motion-Not-A-Project', summary: 'A standalone motion exploration. Visit the original Behance project to see the work in motion.', color: '#dcd8ef' },
  { slug: 'tries', name: 'Tries', subtitle: 'An exploration in interface design.', category: 'app', type: 'UI/UX · Interface design', scope: 'UI/UX design project', source: '144376017/Tries-UIUX-Design', summary: 'A UI/UX design project exploring the Tries interface. The original presentation is available on Behance.', color: '#dedfd3' },
  { slug: 'sheeps-fight', name: 'Sheeps Fight', subtitle: 'A more playful kind of interface.', category: 'play', type: 'Game · UI/UX', scope: 'Game interface design', source: '144350819/GAME-UXUI-SHEEPS-FIGHT', summary: 'A game UI/UX project exploring a playful interface for Sheeps Fight.', color: '#c8dfba' },
].map(p => ({ ...p, image: p.image || `/projects/${p.slug}.webp`, url: p.url || base + p.source }));
